const express = require("express");
const router = express.Router();

const utilisateur = require("../Controler/utilisateur");
const voiture = require("../Controler/voiture");
const trajet = require("../Controler/trajet");
const poste = require("../Controler/poste");
const poids = require("../Controler/poids");
const place = require("../Controler/place");
const employe = require("../Controler/employe");
const colis = require("../Controler/colis");
const depense = require("../Controler/depense");
const paiement = require("../Controler/paimen");
const reserver = require("../Controler/reserver");
const voyage = require("../Controler/voyage");
const tableauBord = require("../Controler/Tableau_bord");

router.post("/createUtilisateur/", utilisateur.createUtilisateur);
router.put("/updateUtilisateur/:id", utilisateur.updateUtilisateur);
router.delete("/deleteUtilisateur/:id", utilisateur.deleteUtilisateur);
router.get("/getAllUser/", utilisateur.getAllUtilisateurs);
//router.get("/rechercheUser/:id",utilisateur.getUtilisateurById);
router.post("/createVoiture/", voiture.createVoiture);
router.put("/updateVoiture/:id", voiture.updateVoiture);
router.delete("/deleteVoiture/:id", voiture.deleteVoiture);
router.get("/getAllVoiture/", voiture.getAllVoiture);
//router.get("/rechercheVoiture/:id",voiture.getVoitureById);
router.post("/createTrajet/", trajet.createTrajet);
router.put("/updateTrajet/:id", trajet.updateTrajet);
router.delete("/deleteTrajet/:id", trajet.deleteTrajet);
router.get("/getAllTrajet/", trajet.getAllTrajet);
//router.get("/rechercheTrajet/:id",trajet.getTrajetById);
router.post("/createPoste/", poste.createPoste);
router.put("/updatePoste/:id", poste.updatePoste);
router.delete("/deletePoste/:id", poste.deletePoste);
router.get("/getAllPoste/", poste.getAllPoste);
//router.get("/recherchePoste/:id",poste.getPosteById);
router.post("/createPoids/", poids.createPoids);
router.put("/updatePoids/:id", poids.updatePoids);
router.delete("/deletePoids/:id", poids.deletePoids);
router.get("/getAllPoids/", poids.getAllPoids);
//router.get("/recherchePoids/:id",poids.getPoidsById);
router.post("/createPlace/", place.createPlace);
router.put("/updatePlace/:id", place.updatePlace);
router.delete("/deletePlace/:id", place.deletePlace);
router.get("/getAllPlace/", place.getAllPlace);
//router.get("/recherchePlace/:id",place.getPlaceById);
router.get(
  "/getVoituresAvecPlacesOccupees/",
  place.getVoituresAvecPlacesOccupees
);
router.post("/createEmploye/", employe.createEmploye);
router.put("/updatEmploye/:id", employe.updateEmploye);
router.delete("/deleteEmploye/:id", employe.deleteEmploye);
router.get("/getAllEmploye/", employe.getAllEmployes);
//router.get("/rechercheEmploye/:id",employe.getEmployeById);
router.post("/createColis/", colis.createColis);
// router.put("/updateChauffeur/:id",chauffeur.updateChauffeur);
// router.delete("/deleteChauffeur/:id",chauffeur.deleteChauffeur);
router.get("/getAllColis/", colis.getAllColis);
//router.get("/rechercheColis/:id",colis.getColisById);
router.post("/createDepense/", depense.createDepense);
// router.put("/updateChauffeur/:id",chauffeur.updateChauffeur);
// router.delete("/deleteChauffeur/:id",chauffeur.deleteChauffeur);
router.get("/getAllDepense/", depense.getAllDepense);
//router.get("/rechercheDepense/:id",depense.getDepenseById);
router.post("/createPaiment/", paiement.createPaiment);
// router.put("/updateChauffeur/:id",chauffeur.updateChauffeur);
// router.delete("/deleteChauffeur/:id",chauffeur.deleteChauffeur);
router.get("/getAllPaiment/", paiement.getAllPaiment);
router.post("/createPaiement", paiement.createPaiment);
// router.get("/recherchePaiment/:id",depense.getPaimentById);
router.post("/createReservation/", reserver.createReservation);
// router.put("/updateChauffeur/:id",chauffeur.updateChauffeur);
// router.delete("/deleteChauffeur/:id",chauffeur.deleteChauffeur);
router.get("/getAllReservation/", reserver.getAllReservation);
//router.get("/rechercheReservation/:id",reserver.getReservationById);
router.post("/createVoyage/", voyage.createVoyage);
router.put("/updateVoyage/:id", voyage.updateVoyage);
router.delete("/deleteVoyage/:id", voyage.deleteVoyage);
router.get("/getAllVoyage/", voyage.getAllVoyage);

router.get("/DepensesParJour/", tableauBord.DepensesParJour);
router.get("/PaiementsParJour/", tableauBord.PaiementsParJour);
router.get("/VoyagesParJour/", tableauBord.VoyagesParJour);

module.exports = router;
